wandb_version: 1

LOG_FOLDER:
  desc: null
  value: wandb/
HIDDEN:
  desc: null
  value: 256
MODEL_HIDDEN:
  desc: null
  value: 256
EMBED:
  desc: null
  value: 256
N_CATEGORICALS:
  desc: null
  value: 32
N_CLASSES:
  desc: null
  value: 32
STOCHASTIC:
  desc: null
  value: 1024
DETERMINISTIC:
  desc: null
  value: 256
VALUE_LAYERS:
  desc: null
  value: 2
VALUE_HIDDEN:
  desc: null
  value: 256
PCONT_LAYERS:
  desc: null
  value: 2
PCONT_HIDDEN:
  desc: null
  value: 256
ACTION_SIZE:
  desc: null
  value: 3
ACTION_LAYERS:
  desc: null
  value: 3
ACTION_HIDDEN:
  desc: null
  value: 128
REWARD_LAYERS:
  desc: null
  value: 2
REWARD_HIDDEN:
  desc: null
  value: 256
GAMMA:
  desc: null
  value: 0.99
DISCOUNT:
  desc: null
  value: 0.99
DISCOUNT_LAMBDA:
  desc: null
  value: 0.95
IN_DIM:
  desc: null
  value: 19
num_mini_batch:
  desc: null
  value: 1
use_valuenorm:
  desc: null
  value: true
use_huber_loss:
  desc: null
  value: true
use_clipped_value_loss:
  desc: null
  value: true
huber_delta:
  desc: null
  value: 10.0
contdisc:
  desc: null
  value: false
nums_obs_token:
  desc: null
  value: 12
EMBED_DIM:
  desc: null
  value: 64
OBS_VOCAB_SIZE:
  desc: null
  value: 256
ema_decay:
  desc: null
  value: 0.995
alpha:
  desc: null
  value: 10.0
vq_type:
  desc: null
  value: vq
policy_class:
  desc: null
  value: gaussian
cond_channels:
  desc: null
  value: 256
inner_model_cfg:
  desc: null
  value:
    state_dim: -1
    num_steps_conditioning: 3
    cond_channels: 256
    depths:
    - 2
    - 2
    - 2
    channels:
    - 64
    - 64
    - 64
    attn_depths:
    - 0
    - 0
    - 0
    action_dim: -1
    dim: 128
    dim_mults:
    - 1
    - 4
    - 8
perceiver_cfg:
  desc: null
  value:
    dim: 256
    latent_dim: 512
    num_latents: 32
    depth: 2
    cross_heads: 1
    cross_dim_head: 64
    latent_heads: 8
    latent_dim_head: 64
    attn_dropout: 0.0
    ff_dropout: 0.0
    output_dim: 256
    final_proj_head: true
denoiser_cfg:
  desc: null
  value:
    inner_model:
      state_dim: -1
      num_steps_conditioning: 3
      cond_channels: 256
      depths:
      - 2
      - 2
      - 2
      channels:
      - 64
      - 64
      - 64
      attn_depths:
      - 0
      - 0
      - 0
      action_dim: -1
      dim: 128
      dim_mults:
      - 1
      - 4
      - 8
    perceiver:
      dim: 256
      latent_dim: 512
      num_latents: 32
      depth: 2
      cross_heads: 1
      cross_dim_head: 64
      latent_heads: 8
      latent_dim_head: 64
      attn_dropout: 0.0
      ff_dropout: 0.0
      output_dim: 256
      final_proj_head: true
    sigma_data: 0.5
    sigma_offset_noise: 0.3
num_autoregressive_steps:
  desc: null
  value: 3
sigma_distribution:
  desc: null
  value:
    loc: -0.4
    scale: 1.2
    sigma_min: 0.002
    sigma_max: 20.0
rewendmodel_cfg:
  desc: null
  value:
    lstm_dim: 512
    cond_channels: 128
    depths:
    - 2
    dim: 128
    dim_mults:
    - 1
    attn_depths:
    - 0
    mlp_dim: 512
horizon:
  desc: null
  value: 15
diffusion_sampler_cfg:
  desc: null
  value:
    num_steps_denoising: 4
    sigma_min: 0.002
    sigma_max: 5.0
    rho: 7
    order: 1
    s_churn: 0.0
    s_tmin: 0.0
    s_tmax: .inf
    s_noise: 1.0
    agent_order: default
    loc: -0.4
    scale: 1.2
worldmodel_env_cfg:
  desc: null
  value:
    horizon: 15
    num_batches_to_preload: 10
    diffusion_sampler:
      num_steps_denoising: 4
      sigma_min: 0.002
      sigma_max: 5.0
      rho: 7
      order: 1
      s_churn: 0.0
      s_tmin: 0.0
      s_tmax: .inf
      s_noise: 1.0
      agent_order: default
      loc: -0.4
      scale: 1.2
use_stack:
  desc: null
  value: false
stack_obs_num:
  desc: null
  value: 5
TRANS_EMBED_DIM:
  desc: null
  value: 256
HEADS:
  desc: null
  value: 4
DROPOUT:
  desc: null
  value: 0.1
trans_config:
  desc: null
  value:
    tokens_per_block: 2
    max_blocks: 15
    attention: causal
    num_layers: 6
    num_heads: 4
    embed_dim: 256
    embed_pdrop: 0.1
    resid_pdrop: 0.1
    attn_pdrop: 0.1
rew_end_model_type:
  desc: null
  value: transformer
use_bin:
  desc: null
  value: false
bins:
  desc: null
  value: 256
action_bins:
  desc: null
  value: 256
state_decoder_type:
  desc: null
  value: s + id
MODEL_LR:
  desc: null
  value: 0.0002
ACTOR_LR:
  desc: null
  value: 0.0005
VALUE_LR:
  desc: null
  value: 0.0005
CAPACITY:
  desc: null
  value: 250000
MIN_BUFFER_SIZE:
  desc: null
  value: 5000
MODEL_EPOCHS:
  desc: null
  value: 200
WM_EPOCHS:
  desc: null
  value: 200
PPO_EPOCHS:
  desc: null
  value: 5
MODEL_BATCH_SIZE:
  desc: null
  value: 40
BATCH_SIZE:
  desc: null
  value: 30
ac_batch_size:
  desc: null
  value: 600
SEQ_LENGTH:
  desc: null
  value: 15
N_SAMPLES:
  desc: null
  value: 200
EPOCHS:
  desc: null
  value: 5
TARGET_UPDATE:
  desc: null
  value: 20
clip_param:
  desc: null
  value: 0.1
DEVICE:
  desc: null
  value: cuda:0
GRAD_CLIP:
  desc: null
  value: 100.0
ENTROPY:
  desc: null
  value: 0.001
ENTROPY_ANNEALING:
  desc: null
  value: 1.0
GRAD_CLIP_POLICY:
  desc: null
  value: 10.0
t_bs:
  desc: null
  value: 512
t_lr:
  desc: null
  value: 0.0001
wm_bs:
  desc: null
  value: 64
wm_lr:
  desc: null
  value: 0.0001
wm_weight_decay:
  desc: null
  value: 0.01
max_grad_norm:
  desc: null
  value: 10.0
is_preload:
  desc: null
  value: false
load_path:
  desc: null
  value: null
use_external_rew_model:
  desc: null
  value: false
sample_temperature:
  desc: null
  value: 20.0
critic_average_r:
  desc: null
  value: false
critic_dist_config:
  desc: null
  value:
    symlog_transform: false
    loss_type: regression
    min_v: -10.0
    max_v: 10.0
    bins: 21
tau:
  desc: null
  value: 0.5
ae_grad_acc_steps:
  desc: null
  value: 1
ae_max_grad_norm:
  desc: null
  value: 10.0
ae_steps_first_epoch:
  desc: null
  value: 5000
ae_lr:
  desc: null
  value: 0.0001
ae_opt_cfg:
  desc: null
  value:
    lr: 0.0001
    weight_decay: 0.01
    eps: 1.0e-08
grad_acc_steps:
  desc: null
  value: 1
ema_update_every:
  desc: null
  value: 10
denoiser_opt_mode:
  desc: null
  value: robodreamer
denoiser_max_grad_norm:
  desc: null
  value: 1.0
denoiser_steps_first_epoch:
  desc: null
  value: 200
denoiser_opt_cfg:
  desc: null
  value:
    lr: 0.0001
    weight_decay: 0.01
    eps: 1.0e-08
denoiser_lr_warmup_steps:
  desc: null
  value: 100
remodel_steps_first_epoch:
  desc: null
  value: 200
remodel_steps:
  desc: null
  value: 200
rew_end_model_opt_cfg:
  desc: null
  value:
    lr: 0.0001
    weight_decay: 0.01
    eps: 1.0e-08
remodel_lr_warmup_steps:
  desc: null
  value: 100
remodel_max_grad_norm:
  desc: null
  value: 10.0
update_manner:
  desc: null
  value: REINFORCE
ac_steps_first_epoch:
  desc: null
  value: 5
ac_opt_cfg:
  desc: null
  value:
    lr: 0.0001
    weight_decay: 0.01
    eps: 1.0e-08
ac_lr_warmup_steps:
  desc: null
  value: 100
ac_max_grad_norm:
  desc: null
  value: 10.0
compute_end_in_TD:
  desc: null
  value: false
offline_epochs:
  desc: null
  value: 20
env_name:
  desc: null
  value: HalfCheetah-v2
STATE_DIM:
  desc: null
  value: 17
NUM_AGENTS:
  desc: null
  value: 2
CONTINUOUS_ACTION:
  desc: null
  value: true
ACTION_SPACE:
  desc: null
  value: Box([-1. -1. -1.], [1. 1. 1.], (3,), float32)
ENV_TYPE:
  desc: null
  value: MAMUJOCO
seed:
  desc: null
  value: 23
use_ce_for_cont:
  desc: null
  value: false
load_pretrained:
  desc: null
  value: false
RUN_DIR:
  desc: null
  value: /project/DIMA/0301_results/mamujoco/HalfCheetah-v2-2x3/run2
map_name:
  desc: null
  value: HalfCheetah-v2
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1772376285
    t:
      1:
      - 1
      - 12
      - 30
      - 41
      - 55
      2:
      - 1
      - 12
      - 30
      - 41
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: steps
      6:
      - 3
    - 1: reward
      5: 1
      6:
      - 1
      - 3
    - 1: eval_win_rate
      5: 1
      6:
      - 1
      - 3
    - 1: eval_returns
      5: 1
      6:
      - 1
      - 3
